"""create job tables

Revision ID: 2bd5c3c6e7d7
Revises: 3437823a8b2e
Create Date: 2026-09-15 16:36:04.520019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd5c3c6e7d7'
down_revision: Union[str, Sequence[str], None] = '3437823a8b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'internship', 'temporary', name='employment_type'), nullable=False),
    sa.Column('workplace_type', sa.Enum('onsite', 'hybrid', 'remote', name='workplace_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'closed', 'archived', name='job_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('required_experience', sa.String(length=150), nullable=True),
    sa.Column('required_education', sa.String(length=150), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('positions_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('application_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_questions_id'), 'application_questions', ['id'], unique=False)
    op.create_index(op.f('ix_application_questions_job_id'), 'application_questions', ['job_id'], unique=False)
    op.create_table('job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('skill_type', sa.Enum('required', 'preferred', name='skill_type'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_skills_id'), 'job_skills', ['id'], unique=False)
    op.create_index(op.f('ix_job_skills_job_id'), 'job_skills', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_skills_job_id'), table_name='job_skills')
    op.drop_index(op.f('ix_job_skills_id'), table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_application_questions_job_id'), table_name='application_questions')
    op.drop_index(op.f('ix_application_questions_id'), table_name='application_questions')
    op.drop_table('application_questions')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    sa.Enum('required', 'preferred', name='skill_type').drop(op.get_bind())
    sa.Enum('draft', 'published', 'closed', 'archived', name='job_status').drop(op.get_bind())
    sa.Enum('onsite', 'hybrid', 'remote', name='workplace_type').drop(op.get_bind())
    sa.Enum('full_time', 'part_time', 'contract', 'internship', 'temporary', name='employment_type').drop(op.get_bind())
    # ### end Alembic commands ###
